# Generated by Django 3.2.4 on 2021-06-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='analog',
            field=models.CharField(max_length=255, null=True, verbose_name='Аналог'),
        ),
        migrations.AddField(
            model_name='product',
            name='applicability',
            field=models.CharField(max_length=255, null=True, verbose_name='Применение'),
        ),
        migrations.AddField(
            model_name='product',
            name='filter_size',
            field=models.CharField(max_length=255, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='filter_volume',
            field=models.FloatField(default=0, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='product',
            name='filter_weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='URL'),
        ),
    ]
